### PR TITLE
Precomputation explicit ss

### PR DESCRIPTION
**Pull request by merkste**
#49 reports that the explicit steady-state computation does not converge in certain cases. This PR improves the situation by applying the same precomputation for the power method (_William J. Stewart: Introduction to the Numerical Solution of Markov Chains p. 124_) as the other engines.

### CODE REVIEW

**Comment by kleinj** [comment]
Thanks.

Some preliminary remarks, didn't look at the actual logic yet:

- I think it would make sense to avoid overloading `vmMult` and just add the new method as something like `vmMultPowerSteady` or so.
- Do we need to touch the existing vmMult() method at all?
- For the `vm/mv...` methods in `DTMC`, we recently switched to using `PrimitiveIterator.OfInt`.
  See, e.g., https://github.com/prismmodelchecker/prism/blob/8aec43df690e9e59f7845d26adcd5a9e700d0c20/prism/src/explicit/DTMC.java#L375-L381
 This has the advantage of being compatible with the new SCCInfo method of storing SCCs not in individual BitSets and defines an iteration order as well. In addition, there is already method for `doublesAreClose` taking such an `OfInt` filter, so you don't need to add one for `BitSet`.
- We tried recently to switch to the `forEachTransition` based iteration instead of using `getTransitionIterator` in the generic implementations, as that seems to have better performance.
- You probably don't need to add the `RuntimeException("Not implemented yet")` methods to some of the derived DTMCs, as long as they provide a transition iterator (and they should) it should in principle just work.

I have prepared some extension for the `-exportiterations` functionality, i.e., exporting the iteration vectors to a HTML file, for exporting the iterations for the individual BSCCs during the steady-state computation. Might be helpful for debugging / comparing with the iterations in the symbolic engine.

**Comment by merkste** [comment]
Thanks for your reply. I've updated the PR, comments on each point go below.

* As `vmMult` was only used for steady-state computation, overloading felt quite right. However, we can easily change this to `vmMultSteadyState.`
* I touched the `vmMult` implementations to address several technical issues, e.g.,
  * scope of variables and naming
  * usage of `Arrays#fill` instead of manual loop
  * superflous casts
* Nice to see primitive iterators here. I changed the code accordingly and supplemented `PrismUtils` by a convenience method of `doublesAreClose` that takes an IterableInt.
* I consider using `forEachTransition` for a subsequent PR that brings further improvements
* Indeed. removed.

**Comment by kleinj** [comment]
I'm a bit lost on the logic part, i.e., what you are actually computing in each step. Could you provide some more comments at that level?

I don't understand what you mean with the various 'Assert ...' comments.

From my understanding, in the generator matrix Q, the diagonal value `i,i` is the negated sum of the outgoing probabilities, ignoring the self-loop probabilities. In your `diags`, it's the row sum of all outgoing probabilities? If that is 1 anyways, why do you need to pass it to the vmMult variant at all?

Some further suggestions:
- I would indeed prefer using some other name than `vmMult`, as that's generic and, while it's only used for steady-state in main PRISM, you don't know if there are other use cases in external projects or branches.
- Could we drop the changes to the 'plain' vmMult from this PR? The additions / changes to `PrismUtils` are not necessary as well, you can simply call `.iterator()` from the outside code, no need for the convenience function.
- I would suggest just implementing the `vmMultSteadyStatePower` (whatever it will be called) only in DTMC via the default method and in DTMCSparse (for efficiency), not in all the derived DTMC classes. That way there is less code to review and we currently don't have a way to test using those classes anyways. If the default implementation is fine and their getTransitionsIterator works as expected, the results should be correct.
- Could you switch back the status output (number of iterations, run time) to the way it was before?

Indenting the assignments like
```
res.soln      = soln;
res.numIters  = iters;
```
is not generally used elsewhere in PRISM.

**Comment by kleinj** [comment]
Hi @merkste,

I just pushed the additions to the iterations export (-exportiterations) that allow to get HTML files for the iterations done for each BSCC. This results in a slight merge conflict, but should be easy to fix. Using this, we can do a fine-grained comparison with the iterations done in the symbolic steady state computations.

**Comment by merkste** [comment]
Thanks for the comments. As discussed in detail offline, I did the following modifications:
1. explicit output matches now matches other engines (previously it didn't)
2. The new specialized `vmMult` is now `vmMultPowerSteadyState`
3. Improvements to old `vmMult` is part of the separate PR #60
4. I improved the comments and added an explanation to the symbolic engines as well.
5. I removed the specialized implementation of vmMultPowerSteadyState except for DTMCSparse.
Furthermore, an implementation of `reduceTransitions` became part of the PR. It is used, e.g., for summation of outgoing probabilities.

**Comment by muhrik** [comment]
Hello. 
What is the status on fixing this non-convergence bug?

I was just about to report it because I have just run into this bug myself.
Then I noticed @merkste already reported it months ago.
I would love to see it fixed so that the explicit engine is in as good shape as possible, because our PRISM fork https://github.com/VojtechRehak/prism-gsmp relies on it.

**Comment by kleinj** [comment]
Hi @muhrik,

thanks for the bump. I'm currently doing code review on the logic and am creating some test cases, so we should be able to merge something sooner rather than later.

Cheers,
Joachim

**Comment by kleinj** [comment]
Hi @merkste,

as discussed offline, there is a bug in your proposed solution due to the handling of the passed-in result vector, as the steady-state computations for subsequent BSCCs overwrite the previous results (for -steadystate).

I've fixed this and added some more tweaks on top of your PR, see https://github.com/kleinj/prism/tree/precomputation-explicit-ss-2. In particular:

- Fix handling of the passed-in result vector (don't touch entries outside of the given BSCC)
- Expanded comments
- The `vmMultPowerSteadyState` methods takes the diagonal entries of the generator matrix Q. I found it difficult to track how the self-loop rates (included in the diagonals or not) are handled if those are first added and then substracted again later-on.
- Normalise the solution for a BSCC (as in the symbolic engines)
- Always return the most current values via the result vector
  (previously, and also in `vmMult`, depending on if result=soln or =soln2 in the current
   iteration, the result values reflected either the values after
   the last iteration or the previous iteration). That does not have a significant impact on the
  result as soln/soln2 are epsilon-close on convergence, but seems to be cleaner.

I've also added two simple test cases to provide some basic sanity checking. As we currently have no way of doing approximate comparison of exported `-steadystate` results in `prism-auto`, those concentrate on computation of `S=?[...]` properties, which also excersise the BSCC steady state computations touched by the changes.

In the symbolic engine implementation, the computation of the `delta_t` factor correponds to `delta_t = 1/max E(s)` with `E(s)` being the exit rate from state s, including the self-loops; so in the case of DTMCs this results in always using `delta_t = 0.99` (which is fine). For the explicit engine, the `delta_t` computation mimics this for the moment; it would make sense to see how using the "more aggressive" `delta_t = 1/max |q(s,s)|` factor (as proposed in the Stewart book, where the self-loops are not part of `|q(s,s)|`) fares in practice, but I've wanted to keep that consideration out of this PR.

Visual inspection of the iteration exports for the test cases match those generated by the symbolic engines, both using the `DTMCSparse` implementation and using the "generic" `DTMC` implementation (the latter is not covered by automatic tests). The test case from #49 also converges; I have not yet checked whether the computed steady-state distribution (approximately) matches the values computed with the symbolic engines.

@merkste: Could you have a look? We could then clean-up/combine the PR. I'd like to keep out your proposed `reduce` functionality for the moment; we can discuss and include that later-on.

**Comment by merkste** [comment]
@kleinj Thanks for the intensive code review and the discovery of the bugs. I've merged all the changes and some cleanups into this branch. I also moved `reduceTransitions` to a separate branch to enable a dedicated discussion.

**Comment by kleinj** [comment]
@merkste Thanks, as well for fishing out the `nextInt()` typos.

I noticed two typos in the PrismUtils.java comments ("that that" and "Un"), but I can fix those on merge.

From my side this looks good & ready to merge. @davexparker What do you think?

Afterwards, I'd have a look at wiring up the steady-state stuff for explicit CTMCs as well.

**Pull request merged**
