### PR TITLE
Provide a functional iteration API similar to Stream

### PR DESCRIPTION
**Pull request by merkste**
Java 8 introduced a feature-rich streaming API providing versatile methods like `filter` and `map`. However, Prism relies heavily on iterators and it is non-trivial to move on to Streams. Additionally, in the context of Prism, iterators usually outperform streams.

This PR provides a functional API for working with iterators. Its goals are
* similar to Stream API, e.g., `map`, `filter`, `reduce` etc.
* full support for primitive iterators of `double`, `int` and `long`
* efficient iteration and type safety
* easy to extend

`Reducible` and the derived specializations `FunctionalIterable` and `FunctionalIterator` are the core interfaces that provide the primary protocols:
* _transforming_
  * transforms an iterable/iterator into another iterable/iterator
  * `concat`, `distinct`, `filter`, `map`, `flatMap`, `nonNull`
* _accumulating_
  * does some computation with all elements
  * `allMatch`, `anyMatch`, `asString`, `forEach`, `collect`, `contains`, `count`, `detect`, `reduce`

On top of them are implementations for summation, minimum and such.

For existing iterables and iterators, an efficient wrapping mechanism is provided that is stripped during the actual iteration. Thus, no additional overhead by indirection is impaired. Functional iterables/iterators can either be created by this wrapping mechanism, by unboxing primitive types or element-wise.
```Java
// wrap an existing Iterable or Iterator
FunctionalIterable.Of<?> extended = Reducible.extend(iterable);

// wrap an existing Iterable or Iterator that yields a primitive type, i.e. double, int or long
FunctionalPrimitiveIterable.OfDouble unboxedDoubles = Reducible.unboxDouble(iterableDouble);

// create an empty Iterable or Iterator
FunctionalIterable.Of<?> empty = FunctionalIterable.of();
FunctionalIterable.OfDouble emptyDoubles = FunctionalIterable.ofDouble();

// create an Iterable or Iterator over (an array of) elements
FunctionalIterable.Of<?> empty = FunctionalIterable.of("first", "second", "third");
FunctionalIterable.OfDouble emptyDoubles = FunctionalIterable.ofDouble(1.0, 2.0, 3.0);

```
Below is an example how to use the API to accomplish various tasks.
```Java
// remove null from an Iterable<Object> and drop duplicates
Reducible.extend(objects).nonNull().distinct();

// unbox integers from an Iterator<Integer> and compute the maximum
Reducible.unboxInt(integers).max();

// compute outgoing probabilities of a state s
getTransitionsIterator(s).filter(t -> t.getKey() != s).mapToDouble(t -> t.getValue()).sum();

// compute successor states of a state s in an MDP
new Range(getNumChoices(s)).flatMap(c -> getTransitionIterator(s, c)).map(Entry::getKey).distinct();
```

Integration into existing code is straightforward. Replacing `Iterator`, `PrimitiveIterator` by their counterparts `FunctionalIterable` and `FunctionalPrimitiveIterable` is sufficient. Existing Iterators can either be wrapped or replaced by specialized types from the package.

The implementation is stable now. It was used, e.g., in the experiments for the paper _Computing Conditional Probabilities: Implementation and Evaluation_. Although it is not fully documented yet, I'd like to open this PR early to already spark a discussion. Upcoming features like conditional probabilities and quantiles rely on this API.

This PR mainly adds and changes classes and interfaces in the packages
- `common`
- `common/iterable`

# Changes to existing code

The API enhancements and changes may require minor adaptions to existing code, as seen in the package explicit. Below are explanations of the API changes.

0. General Remarks:
- Avoid using `MappingIterator` directly. Use `Reducible#map` instead.
- Avoid using `FilteringIterator` directly. Use `Reducible#filter` instead.
- Mind the difference between `Reducible#dedupe` and `Reducible#distinct`.

1. Clean up package common/functions
The former distinction into functions and primitive functions was arbitrary.
- `common/functions/primitive/PairPredicateInt` > `common/functions/PairPredicateInt`

2. Implement interface PrimitiveIterable
The new interface supersedes the old interfaces for primitive iterables to harmonize it with the Java streams API.
- `IterableDouble` > `PrimitiveIterable.OfDouble`
- `IterableInt` > `PrimitiveIterable.OfInt`
- `IterableLong` > `PrimitiveIterable.OfLong`

3. API changes in EmptyIterable and EmptyIterator
Method names should start in lower case.
- `EmptyIterable#Of` > `EmptyIterable#of`
- `EmptyIterable#OfDouble` > `EmptyIterable#ofDouble`
- `EmptyIterable#OfInt` > `EmptyIterable#ofInt`
- `EmptyIterable#OfLong` > `EmptyIterable#ofLong`
- `EmptyIterator#Of` > `EmptyIterator#of`
- `EmptyIterator#OfDouble` > `EmptyIterator#ofDouble`
- `EmptyIterator#OfInt` > `EmptyIterator#ofInt`
- `EmptyIterator#OfLong` > `EmptyIterator#ofLong`

4. API changes in FilteringIterator
Adapt to Java semantics of dedupe and distinct.
- `dedupe`: Remove consecutive duplicate elements.
- `distinct`: Remove duplicate elements.

5. API changes in MappingIterator
The names of the inner classes should reveal the mapping types.
- `From` > `ObjToObj`
- `ToDouble` > `ObjToDouble`
- `ToInt` > `ObjToInt`
- `ToLong` > `ObjToLong`
- `FromDouble` > `DoubleToObj`
- `FromDoubleToDouble` > `DoubleToDouble`
- `FromDoubleToInt` > `DoubleToInt`
- `FromDoubleToLong` > `DoubleToLong`
- `FromInt` > `IntToObj`
- `FromIntToDouble` > `IntToDouble`
- `FromIntToInt` > `IntToInt`
- `FromIntToLong` > `IntToLong`
- `FromLong` > `LongToObj`
- `FromLongToDouble` > `LongToDouble`
- `FromLongToInt` > `LongToInt`
- `FromLongToLong` > `LongToLong`
Remove duplicated unboxing methods.
- `#toDouble` > use `#unboxDouble` in `PrimitiveIterable` or `Reducible`
- `#toInt`    > use `#unboxInt` in `PrimitiveIterable` or `Reducible`
- `#toLong`   > use `#unboxLong` in `PrimitiveIterable` or `Reducible`

### CODE REVIEW

**Comment by merkste** [comment]
Rebased branch on current master and fixed some import issues.

**Comment by davexparker** [comment]
Thanks @merkste. This all looks great. One issue to resolve: The PR claims "does not yet touch the rest of Prism", but this is not the case. In particular, various class in `src/explicit` change. It would be good to clarify if these are essential within the same PR/commits, or whether these could be separated out. The latter is preferable. And either way, it would be good to document what changes are needed (or preferred) in the commit messages, so that others merging these changes into their branches know what to change.

**Comment by merkste** [comment]
Dear @davexparker, thanks for your remarks. You're right, the comment stating that the rest of PRISM is not touched became outdated in the history of this #PR. I documented the changes as requested in both the PR and the commit messages. Although the list seems to be long, the impact is very little as it effects only a few places where I used the old "in-preview" interfaces, e.g., in model views.

Additionally, the changes fix quite a bunch of bugs and #164 provides some confidence that the code actually behaves as it should.

**Comment by davexparker** [comment]
Merged to master as 19c30dba1.

**Pull request closed without merging**
