### PR TITLE
support for aarch64

### PR DESCRIPTION
**Pull request by t-nojiri**
This is a fix for building on aarch64.

### CODE REVIEW

**Comment by davexparker** [comment]
Thanks for this @t-nojiri. The `ARCH` variable is passed to (and used in):

* `ext/lp_solve_5.5_java/lib/build`
* `ext/lpsolve55/src/lp_solve_5.5/lpsolve55/ccc`

So I guess the same changes should be made there?

I don't have an ARM machine to test on. Could you please confirm that `make tests` runs without error?

**Comment by t-nojiri** [comment]
There were no errors in make tests.
  Result: 0.16666650772094727 (value in the initial state) Testing  
  result: PASS

**Comment by davexparker** [comment]
Thanks. That's `make test`, not `make tests`. Just a quick check that it compiled, rather than the full test suite.

**Comment by davexparker** [comment]
Thanks again for this @t-nojiri. I tested it on an aarch64 VM and all tests ran ok. I'm merging it to `master` now (with extra fixes for `ext`, as mentioned above).

**Pull request closed without merging**
