### PR TITLE
Implement short-circuiting of &,|,->,? during (explicit engine) model checking.

### PR DESCRIPTION
**Pull request by davexparker**
As raised in #211.

### CODE REVIEW

**Comment by merkste** [comment]
It would be good to extend the test case to the other operators, too. This ensures that we do not break short-circuiting unnoticed in the future.

**Comment by merkste** [comment]
Diff of the chances above: [pr-shortcircuit-mc.txt](https://github.com/prismmodelchecker/prism/files/10768419/pr-shortcircuit-mc.txt)

**Review by merkste — COMMENTED** [review]
Main change is the use of plain `BitSet`s in the signature to avoid polluting the call site. Otherwise technical changes to creation of `BitSet`s and scoping in loops.

**Comment by davexparker** [comment]
All good. Thanks @merkste. Updated PR (+ extended tests) force pushed.

**Pull request merged**
